version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: bvdilshan/crust-backend:latest
    container_name: crust-backend-prod
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
